[prune]
  go-tests = true
  unused-packages = true
  non-go = true
  # For proto files
  [[prune.project]]
    name = "github.com/gogo/protobuf"
    non-go = false
  [[prune.project]]
    name = "github.com/tendermint/abci"
    non-go = false
  [[prune.project]]
    name = "github.com/tendermint/tmlibs"
    non-go = false

# From Tendermint
[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "=0.21.0"

[[constraint]]
  name = "github.com/tendermint/go-amino"
  version = "=0.9.9"

[[constraint]]
  name = "github.com/tendermint/iavl"
  version = "=0.8.0-rc0"

[[override]]
  name = "github.com/tendermint/tmlibs"
  version = "~0.8.4"

# We don't care which version Tendermint wants
[[override]]
  name = "github.com/gogo/protobuf"
  version = "~1.1.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "~1.1.0"

[[override]]
  name = "google.golang.org/grpc"
  version = "~1.13.0"
