
[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.22.0-rc2"

[[constraint]]
  name = "github.com/tendermint/go-amino"
  version = "0.10.1"

[[constraint]]
  name = "github.com/tendermint/iavl"
  version = "0.9.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/tmthrgd/go-hex"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/mr-tron/base58"

# override is needed because of grpc-middleware having constraint on master branch
[[override]]
  version = "v1.1.0"
  name = "github.com/golang/protobuf"


[prune]
  go-tests = true
  unused-packages = true
